site_name: DS4Windows Docs
repo_url: https://github.com/CircumSpector/DS4WDocs
site_description: DS4Windows documentation website. Guides, FAQs, troubleshooting articles and more.

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      toggle:
       icon: material/weather-night
       name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ryochan7/DS4Windows
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ds4windows
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCIoUA_XLlCSZbvZGeg3Byeg    
extra_css:
  - stylesheets/glightbox.css
extra_javascript:
  - javascripts/glightbox.js
  - javascripts/main.js

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.tabbed:
  - pymdownx.superfences:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details:
  - pymdownx.tilde:
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true

nav:
  - Welcome: index.md
  - About DS4Windows:
    - 'about/index.md'
    - 'about/latest-version.md'
    - 'about/supported-gamepads.md'
    - 'about/companion-drivers.md'
    - 'about/faq.md'
  - Community and Support: community-support.md
  - Guides:
    - 'guides/index.md'
    - The basics:
      - 'guides/install-setup.md'
      - 'guides/connecting-controllers.md'
      - 'guides/solving-double-input.md'
    - Customization:
      - 'guides/p-editor-axis.md'
    - Backup/uninstall instructions:  
      - 'guides/managing-user-data.md'
      - 'guides/uninstalling-ds4windows.md'
    - Advanced guides:
      - 'guides/prevent-steam-conflict.md'
      - 'guides/ds4w-custom-name.md'
  - Troubleshooting:
    - 'troubleshooting/index.md'
    - 'troubleshooting/ds4w-does-not-run.md'
    - Physical controller detection, connection and related issues:
      - 'troubleshooting/ds4w-controller-detection.md'
      - 'troubleshooting/controllers-check.md'
      - 'troubleshooting/bt-connection-issues.md'
      - 'troubleshooting/input-delay-bt.md'
    - Virtual controller usage in games and related issues: 
      - 'troubleshooting/virtual-controller-failure.md'
      - 'troubleshooting/games-controller-detection.md'
      - 'troubleshooting/xinput-slots-order.md'
      - 'troubleshooting/misbehaving-controller-ingame.md'
    - Double input related issues:
      - 'troubleshooting/hidhide-troubleshoot.md'
      - 'troubleshooting/hide-ds4-option.md'
    - 'troubleshooting/kb-mouse-issues.md'
    - 'troubleshooting/steam-related.md'
    - 'troubleshooting/audio-related.md'
    - Advanced:
      - 'troubleshooting/tracing-guide.md'
  - Other:
    - "other/index.md"
    - "other/how-to-check-architecture.md"
    - "other/under-construction.md"
